env:
  - name: DB_HOST
    value: "terraform-20251006022401200400000001.c5syg40e8lbk.us-east-1.rds.amazonaws.com"
  - name: SPRING_DATASOURCE_URL
    # Ajustado para produtos_db conforme o console RDS
    value: "jdbc:postgresql://$(DB_HOST):5432/produtos_db"
  - name: SPRING_DATASOURCE_USERNAME
    # Ajustado para postgres_admin conforme o console RDS
    value: "postgres_admin"
  - name: SPRING_DATASOURCE_PASSWORD
    value: "spoospoo" # Verifique se esta é a senha que você definiu para o postgres_admin