apiVersion: v1
kind: Service
metadata:
  name: minha-app-produtos-service
spec:
  selector:
    app: minha-app-produtos
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  # Usando LoadBalancer para expor o servi√ßo externamente na AWS
  type: LoadBalancer