name: CI/CD da Aplicação

on:
  push:
    branches: [ "main" ] # Adicionei sua branch de trabalho aqui
  pull_request:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push:
    name: Build e Push da Imagem
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login no Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build, tag, e push da imagem
        run: |
          # Usando o nome correto da sua secret: ECR_REPOSITORY_URI
          docker build -t ${{ secrets.ECR_REPOSITORY_URI }}:${{ github.sha }} .
          docker push ${{ secrets.ECR_REPOSITORY_URI }}:${{ github.sha }}

  deploy:
    name: Deploy no Kubernetes
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.event_name == 'push'

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar credenciais AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Configurar kubectl para o EKS
        run: aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name eks-sistemapedidos-eks

      - name: Atualizar imagem no Kubernetes
        run: |
          # Usando o nome correto da sua secret aqui também
          sed -i "s|IMAGEM_PLACEHOLDER|${{ secrets.ECR_REPOSITORY_URI }}:${{ github.sha }}|g" k8s/deployment.yaml

      - name: Aplicar manifestos no Kubernetes
        run: kubectl apply -f k8s/